inherit_from:
  - .rubocop_airbnb.yml

# Rails用に最適化
Rails:
  Enabled: true

# devise
Airbnb/ClassOrModuleDeclaredInWrongFile:
  Exclude:
    - 'app/controllers/Users/*'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/application_helper.rb'

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
